"""inti database

Revision ID: e23c8b40f8e7
Revises: e704d81f2ba3
Create Date: 2018-10-22 12:06:59.049837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23c8b40f8e7'
down_revision = 'e704d81f2ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('phonenumber', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phonenumber')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
